version: '2.1'

services:
  test_service:
    container_name: cont1
    build: cont1/.
    ports:
     - "8080:8080"
    networks:
      vpcbr:
        ipv4_address: 10.10.10.50

  test_service2:
    container_name: cont2
    build: cont2/.
    ports:
     - "8081:8081"
    networks:
      vpcbr:
        ipv4_address: 10.10.10.70

networks:
  vpcbr:
    driver: nat
    ipam:
     config:
       - subnet: 10.10.10.0/24
         gateway: 10.10.10.1